l_simp_chinese:
 SETTING_INPUT_CONTEXT_COMMON: "普通"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "#todo 通用输入上下文的键绑定#!"
 SETTING_INPUT_ACTION_PAUSE: "暂停/解除暂停"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "提高速度"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "降低速度"
 SETTING_INPUT_ACTION_SPEED_ONE: "速度1"
 SETTING_INPUT_ACTION_SPEED_TWO: "速度2"
 SETTING_INPUT_ACTION_SPEED_THREE: "速度3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "速度4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "速度5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "播放/暂停音乐"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "下一首音乐"
 SETTING_INPUT_ACTION_CAMERA_UP: "镜头向上移动"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "镜头向左移动"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "镜头向下移动"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "镜头向右移动"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "地点查找器"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "政治"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "财政"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "建筑"
 SETTING_INPUT_ACTION_OPEN_MARKET: "市场"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "军事"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "外交"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "科技"
 SETTING_INPUT_ACTION_OPEN_CULTURE: "文化"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "人口"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "日志"
 SETTING_INPUT_ACTION_OPEN_DECISIONS: "决议"
 SETTING_INPUT_ACTION_MAP_LIST: "统计报表"
 SETTING_INPUT_ACTION_BACK: "后退"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "概览窗口"
 SETTING_INPUT_ACTION_TAB_1: "Tab 1"
 SETTING_INPUT_ACTION_TAB_2: "Tab 2"
 SETTING_INPUT_ACTION_TAB_3: "Tab 3"
 SETTING_INPUT_ACTION_TAB_4: "Tab 4"
 SETTING_INPUT_ACTION_TAB_5: "Tab 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "生产视图"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "政治视图"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "外交视图"
 SETTING_INPUT_ACTION_MILITARY_LENS: "军事视图"
 SETTING_INPUT_ACTION_TRADE_LENS: "贸易视图"
 SETTING_INPUT_ACTION_CONFIRM: "确认"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "当前形势"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "建造队列"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "暂停/继续建造队列"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "转到详情"
 SETTING_INPUT_ACTION_SCROLL_UP: "向上滚动"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "向下滚动"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Debug) gui.debug"
