l_simp_chinese:
 SETTING_AUTOSAVE_TO_CLOUD:0 "自动保存至云端"
 SETTING_SAVE_FILE_FORMAT:0 "默认存档格式"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "这个选项在铁人、云端和调试模式中不生效"
 OPTION_SAVE_FILE_TEXT:0 "文本"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "压缩文本"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "压缩二进制"
 SETTING_TOOLTIP_MODE:0 "弹框提示模式"
 SETTING_TOOLTIP_MODE_TOOLTIP:1 "#T $SETTING_TOOLTIP_MODE$#!\n选择弹框提示如何锁定：\n   #b 鼠标趋向#!——鼠标移动至弹框提示时锁定。\n   #b 时间锁定#!——一定时间后锁定。\n   #b 行动锁定#!——按鼠标中键锁定。"
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "无锁定"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "鼠标趋势"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "动作锁定（鼠标锚点）"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "定时锁定（鼠标锚点）"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "动作锁定"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "定时锁定"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\n设置鼠标悬停后显示弹框提示的延时。"
 SETTING_TOOLTIP_DELAY:0 "显示延迟"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "解锁的延迟"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\n设置弹框提示解锁之前的延时。"
 SETTING_TOOLTIP_LOCK_TIME:0 "锁定的延迟"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\n设置弹框提示锁定之前的延时。"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "已开启时的锁定延时"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n设置已打开另一弹框提示时，弹框提示锁定之前的延时。"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "高级"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "通用"
 SETTINGS_CATEGORY_SFX:1 "音效"
 SETTINGS_CATEGORY_MFX:0 "音乐"
 SETTINGS_CATEGORY_LANGUAGE:0 "语言"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "保存游戏"
 SETTINGS_CATEGORY_TOOLTIPS:0 "弹框提示设置"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "地图控制"
 SETTING_SHADER_QUALITY:0 "着色器质量"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T 着色器质量\n#!决定各种着色器和特效的质量。\n\n#T 高#!以性能为代价提升某些着色器特效的质量。\n\n#T 中#!能获得预期图形体验的默认设置。\n\n#T 低#!这个设置是为低端设备准备的，由于会造成视觉质量的下降并不推荐。为推动图形性能一些着色器被简化了。"
 SETTING_SHOW_NUDITY:0 "显示裸体"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\n设定角色是否会显示裸体。"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "肖像"
 SETTING_SOUNDTRACK:0 "背景音乐"
 SETTING_SOUNDTRACK_TOOLTIP:0 "总体的背景音乐"
 SETTING_MUSIC_STINGERS:0 "短乐句"
 SETTING_MUSIC_STINGERS_TOOLTIP:0 "简短的乐句，强化游玩体验"
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "音乐"
 SETTING_AMBIENT:0 "环境音效"
 SETTING_MUSIC_TOOLTIP:0 "#T 音乐音量\n#!设置音乐的音量。"
 SETTING_AMBIENT_TOOLTIP:0 "#T 环境音量\n#!设置环境音效的音量。"
 
 SETTING_MAP_TOOLTIP_DELAY:0 "地图弹框提示延迟"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_MAP_TOOLTIP_DELAY$#!\n设置地图弹框提示出现前的延迟时间。"

 color_blind_mode_test:0 "测试"
