l_korean:
 SETTING_INPUT_CONTEXT_COMMON: "일반"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "일반적인 입력 상황에 대한 키를 지정합니다."
 SETTING_INPUT_ACTION_PAUSE: "일시 정지 / 일시 정지 해제"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "속도 증가"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "속도 감소"
 SETTING_INPUT_ACTION_SPEED_ONE: "속도 1"
 SETTING_INPUT_ACTION_SPEED_TWO: "속도 2"
 SETTING_INPUT_ACTION_SPEED_THREE: "속도 3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "속도 4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "속도 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "음악 재생/일시 정지"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "다음 음악 트랙"
 SETTING_INPUT_ACTION_CAMERA_UP: "카메라 위로 이동"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "카메라 왼쪽으로 이동"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "카메라 아래로 이동"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "카메라 오른쪽으로 이동"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "장소 탐색기"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "정치"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "예산"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "건물"
 SETTING_INPUT_ACTION_OPEN_MARKET: "시장"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "군사"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "외교"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "기술"
 SETTING_INPUT_ACTION_OPEN_SOCIETY: "사회"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "인구"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "일지"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "세력 블록"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "기업"
 SETTING_INPUT_ACTION_MAP_LIST: "장부"
 SETTING_INPUT_ACTION_BACK: "뒤로"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "아웃라이너"
 SETTING_INPUT_ACTION_TAB_1: "탭 1"
 SETTING_INPUT_ACTION_TAB_2: "탭 2"
 SETTING_INPUT_ACTION_TAB_3: "탭 3"
 SETTING_INPUT_ACTION_TAB_4: "탭 4"
 SETTING_INPUT_ACTION_TAB_5: "탭 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "생산 돋보기"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "정치 돋보기"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "외교 돋보기"
 SETTING_INPUT_ACTION_MILITARY_LENS: "군사 돋보기"
 SETTING_INPUT_ACTION_TRADE_LENS: "무역 돋보기"
 SETTING_INPUT_ACTION_CONFIRM: "확인"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "현재 상황"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "건설 대기열"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "건설 대기열 일시 정지/일시 정지 해제"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "세부 사항으로 이동"
 SETTING_INPUT_ACTION_SCROLL_UP: "위로 스크롤"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "아래로 스크롤"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(디버그) gui.debug"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "아웃라이너에 고정 표시"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "아웃라이너에 경제 표시"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "아웃라이너에 정치 표시"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "아웃라이너에 외교 표시"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "아웃라이너에 군사 표시"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "아웃라이너에 모두 표시"
 SETTING_INPUT_ACTION_TOGGLE_PIN: "고정 토글"
 SETTING_INPUT_ACTION_ZOOM_TO: "확대 -"
