l_korean:
 SETTING_AUTOSAVE_TO_CLOUD: "클라우드에 자동 저장"
 SETTING_SAVE_FILE_FORMAT: "기본 저장 형식"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "본 옵션은 철인, 클라우드, 디버그 모드에서만 수정할 수 있습니다."
 OPTION_SAVE_FILE_TEXT: "텍스트"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "잠긴 텍스트"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "잠긴 2진수"
 SETTING_TOOLTIP_MODE: "툴팁 모드"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\n툴팁 고정 방식을 설정합니다.\n   #b 마우스 움직임#! - 마우스 커서를 툴팁으로 가져가면 고정합니다.\n   #b 타이머 고정식#! - 일정한 시간이 지나면 고정합니다.\n   #b 동작 고정식#! - 마우스 가운데 버튼으로 고정합니다.\n   #b 타이머 또는 동작 고정식#! - 타이머 고정식 또는 동작 고정식을 사용할 수 있습니다."
 SETTING_TOOLTIP_MODE_NO_LOCK: "잠금 없음"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "마우스 움직임"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "동작 고정식 (마우스 앵커)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "타이머 고정식 (마우스 앵커)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "동작 고정식"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "타이머 고정식"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "타이머 또는 동작 고정식"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\n툴팁에 커서를 올렸을 때 몇 초 후에 툴팁을 표시할지 설정합니다."
 SETTING_TOOLTIP_DELAY: "지연 시간 표시"
 SETTING_TOOLTIP_UNLOCK_TIME: "잠금 해제 지연 시간"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\n툴팁이 잠금 해제되기까지 걸리는 지연 시간을 설정합니다."
 SETTING_TOOLTIP_LOCK_TIME: "잠금 지연 시간"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\n툴팁이 잠금되기까지 걸리는 지연 시간을 설정합니다."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "잠금 후 열림 지연 시간"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n이미 다른 툴팁이 표시된 상태에서 툴팁이 잠금되기까지 걸리는 지연 시간을 설정합니다."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "고급"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "일반"
 SETTINGS_CATEGORY_SFX: "효과음"
 SETTINGS_CATEGORY_MFX: "음악"
 SETTINGS_CATEGORY_LANGUAGE: "언어"
 SETTINGS_CATEGORY_SAVE_GAMES: "저장된 게임"
 SETTINGS_CATEGORY_TOOLTIPS: "툴팁 설정"
 SETTINGS_CATEGORY_MAP_CONTROLS: "지도 조작"
 SETTINGS_CATEGORY_MAPMODES: "지도 모드"
 SETTING_SHADER_QUALITY: "셰이더 품질"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T 셰이더 품질\n#!여러 셰이더와 효과의 품질을 결정합니다.\n\n#T 높음:#! 퍼포먼스는 저하되지만 일부 셰이더 효과의 품질이 향상됩니다.\n\n#T 보통:#! 의도한 대로 그래픽 경험을 할 수 있는 기본 설정입니다.\n\n#T 낮음:#! 사양이 낮은 기기를 위한 설정으로, 시각 품질이 낮아지므로 권장되는 옵션은 아닙니다. 그래픽 퍼포먼스 향상을 위해 각종 셰이더가 단순화됩니다."
 SETTING_SHOW_NUDITY: "누드 표시"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\n인물 누드를 표시할지 설정합니다."
 SETTING_VALUE_HOURS: "$VALUE|0$시간"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "낮밤 주기"
 SETTING_DAYNIGHT_CYCLE: "낮밤 주기 활성화"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\n태양의 움직임에 따른 낮밤 주기를 활성화합니다."
 SETTING_DAYNIGHT_SYSTEMTIME: "현지 시간 동기화 활성화"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\n낮밤 주기 속도와 시간을 컴퓨터 현지 시간에 동기화합니다.\n\n#!시뮬레이션 속도 설정을 덮어씁니다."
 SETTING_DAYNIGHT_SPEED: "시뮬레이션 속도"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\n낮밤 주기 전환 속도를 설정합니다.#!"
 SETTING_SUN_DURATION: "낮 시간"
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\n하루 중 낮 시간의 길이를 설정합니다."
 SETTING_SUNRISE_TIME: "일출 시간"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\n해가 뜨는 시간을 설정합니다.\n\n#!현지 시간 동기화 활성화 시에만 사용됩니다.#!"
 SETTING_DAYNIGHT_SET_TIME: "수동 시간 활성화"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\n낮 시간을 특정한 시간으로 설정합니다.\n\n#!시뮬레이션 속도와 현지 시간 동기화 설정을 덮어씁니다."
 SETTING_SUNRISE_SET_TIME_HOUR: "수동 시간 설정"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\n시간을 해당 시각에 고정합니다.\n\n#!수동 시간 활성화 시에만 사용됩니다.#!"
 SETTING_BUILDINGS_CUTOFF: "멀리 떨어진 건물 표시 완화"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP: "#T $SETTING_BUILDINGS_CUTOFF$#!\n지도에서 카메라와 멀리 떨어진 건물을 적게 표시합니다.\n\n활성화 시 퍼포먼스가 향상됩니다."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "초상화"
 SETTING_SOUNDTRACK: "배경 음악"
 SETTING_SOUNDTRACK_TOOLTIP: "일반 배경 음악"
 SETTING_MUSIC_STINGERS: "음악 스팅"
 SETTING_MUSIC_STINGERS_TOOLTIP: "게임플레이에 잔재미를 더해주는 짤막한 음악입니다."
 #Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "음악"
 SETTING_AMBIENT: "환경음"
 SETTING_MUSIC_TOOLTIP: "#T 음악 음량\n#!음악의 음량을 설정합니다."
 SETTING_AMBIENT_TOOLTIP: "#T 환경음 음량\n#!환경음의 음량을 설정합니다."
 SETTING_MAP_TOOLTIP_DELAY: "지도 툴팁 지연 시간"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\n지도 툴팁을 표시하기까지 걸리는 지연 시간을 설정합니다."
 SETTING_MAP_MODE_DELAY: "지도 모드 지연 시간"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "새로운 지도 모드로 전환하기까지 걸리는 지연 시간을 설정합니다. (초 단위)"
 SETTING_MAP_MODE_FADE_IN: "지도 모드 페이드 인"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "기존 지도 모드가 페이드 아웃된 후 새로운 지도 모드가 페이드 인되기까지 걸리는 시간을 설정합니다. (초 단위)"
 SETTING_MAP_MODE_FADE_OUT: "지도 모드 페이드 아웃"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "새로운 지도 모드를 적용한 후 현재 지도 모드가 페이드 아웃되기까지 걸리는 시간을 설정합니다. (초 단위)"
 SETTING_OCCUPATION_STRIPES: "줄무늬 점유 시각 효과"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\n국기 텍스처 대신 색상 줄무늬를 지도에서 점유의 시각적 표시로 사용합니다."
 SETTING_PORTRAIT_RENDER_SCALE: "초상화 렌더 스케일링"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\n렌더링 결과를 업스케일링하여 인물 초상화를 더욱더 세밀하게 표시합니다. 단, 렌더링 퍼포먼스가 저하됩니다."
 OPTION_PORTRAIT_RENDER_SCALE_NONE: "×1.0 - 없음"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "×1.5 - 중간"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "×2.0 - 높음"
 ui_skin_theme: "사용자 인터페이스"
 ui_skin_theme_desc: "게임 내 버튼, 프레임, 창, 제목 등으로 구성됩니다."
 papermap_theme: "종이 지도"
 papermap_theme_desc: "화면 축소 시 표시되는 지도입니다."
 table_top_theme: "테이블탑"
 table_top_theme_desc: "지도에서 카메라를 최대한 축소할 경우, 화면 상단과 하단에 해당 테이블이 표시됩니다."
 table_asset_1_theme: "테이블 오브젝트 (왼쪽 상단)"
 table_asset_1_theme_desc: "화면 축소 시 지도 옆 테이블의 왼쪽 상단에 표시되는 오브젝트입니다."
 table_asset_2_theme: "테이블 오브젝트 (오른쪽 상단)"
 table_asset_2_theme_desc: "화면 축소 시 지도 옆 테이블의 오른쪽 상단에 표시되는 오브젝트입니다."
 table_asset_3_theme: "테이블 오브젝트 (왼쪽 하단)"
 table_asset_3_theme_desc: "화면 축소 시 지도 옆 테이블의 왼쪽 하단에 표시되는 오브젝트입니다."
 table_asset_4_theme: "테이블 오브젝트 (오른쪽 하단)"
 table_asset_4_theme_desc: "화면 축소 시 지도 옆 테이블의 오른쪽 하단에 표시되는 오브젝트입니다."
 building_sets_themes: "건물 세트"
 color_blind_mode_test: "테스트"
