l_polish:
 SETTING_INPUT_CONTEXT_COMMON: "Standardowe"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "Przypisania klawiszy – standardowe dane wejściowe"
 SETTING_INPUT_ACTION_PAUSE: "Wstrzymaj/wznów"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "Zwiększ szybkość"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "Zmniejsz szybkość"
 SETTING_INPUT_ACTION_SPEED_ONE: "Szybkość 1"
 SETTING_INPUT_ACTION_SPEED_TWO: "Szybkość 2"
 SETTING_INPUT_ACTION_SPEED_THREE: "Szybkość 3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "Szybkość 4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "Szybkość 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Odtwarzaj/wstrzymaj muzykę"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Następny utwór"
 SETTING_INPUT_ACTION_CAMERA_UP: "Przesuń kamerę w górę"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "Przesuń kamerę w lewo"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "Przesuń kamerę w dół"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "Przesuń kamerę w prawo"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Wyszukiwarka lokalizacji"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Polityka"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Budżet"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Budynki"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Rynek"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Wojsko"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Dyplomacja"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Technologia"
 SETTING_INPUT_ACTION_OPEN_SOCIETY: "Społeczeństwo"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "Populacja"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Dziennik"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Blok mocarstw"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Firmy"
 SETTING_INPUT_ACTION_MAP_LIST: "Księga rachunkowa"
 SETTING_INPUT_ACTION_BACK: "Wstecz"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Przybornik"
 SETTING_INPUT_ACTION_TAB_1: "Karta 1"
 SETTING_INPUT_ACTION_TAB_2: "Karta 2"
 SETTING_INPUT_ACTION_TAB_3: "Karta 3"
 SETTING_INPUT_ACTION_TAB_4: "Karta 4"
 SETTING_INPUT_ACTION_TAB_5: "Karta 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Obiektyw Produkcja"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Obiektyw Polityka"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Obiektyw Dyplomacja"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Obiektyw Wojsko"
 SETTING_INPUT_ACTION_TRADE_LENS: "Obiektyw Handel"
 SETTING_INPUT_ACTION_CONFIRM: "Zatwierdź"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Bieżąca sytuacja"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "Kolejka budowy"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "Wstrzymaj/wznów kolejkę budowy"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Przejdź do szczegółów"
 SETTING_INPUT_ACTION_SCROLL_UP: "Przewiń w górę"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Przewiń w dół"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Debug) gui.debug"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "Pokaż przypięte w przyborniku"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "Pokaż gospodarkę w przyborniku"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "Pokaż politykę w przyborniku"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "Pokaż dyplomację w przyborniku"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "Pokaż wojsko w przyborniku"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "Pokaż wszystko w przyborniku"
 SETTING_INPUT_ACTION_TOGGLE_PIN: "Przełączenie przypięcia"
 SETTING_INPUT_ACTION_ZOOM_TO: "Przybliżenie"
