l_polish:
 SETTING_AUTOSAVE_TO_CLOUD: "Automatyczny zapis w chmurze"
 SETTING_SAVE_FILE_FORMAT: "Domyślny format zapisu"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Ta opcja nie jest wykorzystywana w trybie Ironman, w trybie zapisu w chmurze oraz w trybie debugowania"
 OPTION_SAVE_FILE_TEXT: "Plik tekstowy"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Skompresowany plik tekstowy"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Skompresowany plik binarny"
 SETTING_TOOLTIP_MODE: "Tryb podpowiedzi"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nZdecyduj, w jaki sposób blokować podpowiedzi:\n   #b Zachowanie kursora myszy#! – Blokada podpowiedzi następuje po przesunięciu kursora myszy w jej kierunku.\n   #b Blokada względem czasu#! – Podpowiedź zostaje zablokowana po upływie określonego czasu.\n   #b Blokada względem działania#! – Blokada następuje po naciśnięciu środkowego przycisku myszy.\n   #b Blokada względem czasu lub działania#! – Podpowiedź można zablokować, korzystając z blokady względem czasu lub blokady względem działania."
 SETTING_TOOLTIP_MODE_NO_LOCK: "Brak blokady"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Zachowanie kursora myszy"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Blokada względem działania (zakotwiczenie myszy)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Blokada względem czasu (zakotwiczenie myszy)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Blokada względem działania"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Blokada względem czasu"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Blokada względem czasu lub działania"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nOkreśla opóźnienie, z jakim wyświetla się podpowiedź po wskazaniu elementu kursorem myszy."
 SETTING_TOOLTIP_DELAY: "Opóźnienie wyświetlenia"
 SETTING_TOOLTIP_UNLOCK_TIME: "Opóźnienie odblokowania"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nUstawia opóźnienie przed odblokowaniem podpowiedzi."
 SETTING_TOOLTIP_LOCK_TIME: "Opóźnienie zablokowania"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nUstawia opóźnienie przed zablokowaniem podpowiedzi."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Opóźnienie zablokowania (otwarta podpowiedź)"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nUstawia opóźnienie przed zablokowaniem podpowiedzi, kiedy inna podpowiedź jest już otwarta."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Zaawansowane"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Ogólne"
 SETTINGS_CATEGORY_SFX: "Efekty dźwiękowe"
 SETTINGS_CATEGORY_MFX: "Muzyka"
 SETTINGS_CATEGORY_LANGUAGE: "Język"
 SETTINGS_CATEGORY_SAVE_GAMES: "Zapisy gry"
 SETTINGS_CATEGORY_TOOLTIPS: "Ustawienia podpowiedzi"
 SETTINGS_CATEGORY_OUTLINER: "Przybornik"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Sterowanie na mapie"
 SETTINGS_CATEGORY_MAPMODES: "Tryby mapy"
 SETTING_SHADER_QUALITY: "Jakość shaderów"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Jakość shaderów\n#!Określa jakość różnorakich shaderów i efektów.\n\n#T Wysoka:#! poprawia jakość niektórych efektów shaderów kosztem wydajności.\n\n#T Średnia:#! domyślne ustawienie grafiki.\n\n#T Niska:#! ustawienie przeznaczone dla maszyn o niższej wydajności – nie jest zalecane ze względu na pogorszenie jakości obrazu. Aby zwiększyć wydajność grafiki, wiele shaderów zostaje uproszczonych."
 SETTING_SHOW_NUDITY: "Pokazuj nagość"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nOkreśla, czy postacie mogą być pokazywane nago."
 SETTING_VALUE_HOURS: "$VALUE|0$ godz."
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "Cykl dnia i nocy"
 SETTING_DAYNIGHT_CYCLE: "Włącz cykl dnia i nocy"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\nWłącza odzwierciedlający ruch słońca cykl dnia i nocy."
 SETTING_DAYNIGHT_SYSTEMTIME: "Włącz synchronizację z czasem lokalnym"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nSynchronizuje szybkość i czas cyklu dnia i nocy z czasem lokalnym komputera.\n\n#!Spowoduje to nadpisanie ustawienia szybkości symulacji."
 SETTING_DAYNIGHT_SPEED: "Szybkość symulacji"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\nOkreśla szybkość, z jaką dzień zmienia się w noc i odwrotnie.#"
 SETTING_SUN_DURATION: "Godziny słoneczne"
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\nOkreśla, przez ile godzin dziennie świeci słońce."
 SETTING_SUNRISE_TIME: "Czas wschodu słońca"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\nOkreśla godzinę, o której wschodzi słońce.\n\n#!Z tego ustawienia można korzystać tylko po włączeniu synchronizacji z czasem lokalnym.#!"
 SETTING_DAYNIGHT_SET_TIME: "Włącz własne ustawienie czasu"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\nOkreśla porę dnia, umożliwiając wybór konkretnej godziny.\n\n#!Spowoduje to nadpisanie ustawień szybkości symulacji i synchronizacji z czasem lokalnym."
 SETTING_SUNRISE_SET_TIME_HOUR: "Własne ustawienie godziny"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nBlokuje wybraną godzinę.\n\n#!Z tego ustawienia można korzystać tylko po włączeniu własnego ustawienia czasu.#"
 SETTING_BUILDINGS_CUTOFF: "Ukrywanie budynków w oddali"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP: "#T $SETTING_BUILDINGS_CUTOFF$#!\nSprawia, że na mapie widać mniej budynków w zależności od ich odległości od obiektywu kamery.\n\nWłączenie tej opcji może zwiększyć wydajność."
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER: "Powiadomienia po lewej stronie przybornika"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER_TOOLTIP: "#t $SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER$#!\nPrzenieś kanał powiadomień na lewą stronę przybornika"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portrety"
 SETTING_SOUNDTRACK: "Muzyka w tle"
 SETTING_SOUNDTRACK_TOOLTIP: "Ogólna muzyka w tle"
 SETTING_MUSIC_STINGERS: "Efekty muzyczne"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Krótkie muzyczne frazy urozmaicające rozgrywkę"
 #Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Muzyka"
 SETTING_AMBIENT: "Dźwięki otoczenia"
 SETTING_MUSIC_TOOLTIP: "#T Głośność muzyki\n#!Ustawienie to wpływa na głośność muzyki."
 SETTING_AMBIENT_TOOLTIP: "#T Głośność dźwięków otoczenia\n#!Ustawienie to wpływa na głośność dźwięków otoczenia."
 SETTING_MAP_TOOLTIP_DELAY: "Opóźnienie wyświetlania podpowiedzi na mapie"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nUstawia opóźnienie przed wyświetleniem podpowiedzi na mapie."
 SETTING_MAP_MODE_DELAY: "Opóźnienie trybu mapy"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Wyrażony w sekundach czas opóźnienia przed przełączeniem się na nowy tryb mapy"
 SETTING_MAP_MODE_FADE_IN: "Wyświetlenie trybu mapy"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Wyrażony w sekundach czas wygaszenia poprzedniego trybu mapy i wyświetlenia mapy w nowym trybie"
 SETTING_MAP_MODE_FADE_OUT: "Wygaszenie trybu mapy"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Wyrażony w sekundach czas wygaszenia mapy w bieżącym trybie (po upływie czasu opóźnienia trybu mapy), gdy ma zostać zastosowany nowy tryb mapy"
 SETTING_OCCUPATION_STRIPES: "Efekty wizualne okupacji – paski"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nSprawia, że w przypadku okupowanych państw na mapie zamiast flag widoczne są kolorowe paski."
 SETTING_PORTRAIT_RENDER_SCALE: "Skalowanie renderowania portretów"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\nZwiększ poziom szczegółowości portretów postaci, zwiększając skalę rezultatów renderowania kosztem wydajności renderowania."
 OPTION_PORTRAIT_RENDER_SCALE_NONE: "× 1,0 – brak"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "× 1,5 – umiarkowane"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "× 2,0 – wysokie"
 ui_skin_theme: "Interfejs użytkownika"
 ui_skin_theme_desc: "Przyciski, ramki, okna, nagłówki i inne tego typu elementy w grze."
 papermap_theme: "Mapa papierowa"
 papermap_theme_desc: "Mapa, którą widzisz po oddaleniu widoku."
 table_top_theme: "Rzut z góry"
 table_top_theme_desc: "Stół, którego krawędzie zobaczysz u góry i u dołu ekranu, gdy maksymalnie oddalisz widok mapy."
 table_asset_1_theme: "Obiekt na stole (lewy górny róg)"
 table_asset_1_theme_desc: "Obiekt wyświetlany w lewym górnym rogu stołu obok mapy po oddaleniu widoku."
 table_asset_2_theme: "Obiekt na stole (prawy górny róg)"
 table_asset_2_theme_desc: "Obiekt wyświetlany w prawym górnym rogu stołu obok mapy po oddaleniu widoku."
 table_asset_3_theme: "Obiekt na stole (lewy dolny róg)"
 table_asset_3_theme_desc: "Obiekt wyświetlany w lewym dolnym rogu stołu obok mapy po oddaleniu widoku."
 table_asset_4_theme: "Obiekt na stole (prawy dolny róg)"
 table_asset_4_theme_desc: "Obiekt wyświetlany w prawym dolnym rogu stołu obok mapy po oddaleniu widoku."
 building_sets_themes: "Zestaw budynków"
 color_blind_mode_test: "Testuj"
