l_polish:
 SETTING_AUTOSAVE_TO_CLOUD: "Automatyczny zapis w chmurze"
 SETTING_SAVE_FILE_FORMAT: "Domyślny format zapisu"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Ta opcja nie jest wykorzystywana w trybie Ironman, w trybie zapisu w chmurze oraz w trybie debugowania"
 OPTION_SAVE_FILE_TEXT: "Plik tekstowy"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Skompresowany plik tekstowy"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Skompresowany plik binarny"
 SETTING_TOOLTIP_MODE: "Tryb podpowiedzi"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nZdecyduj, w jaki sposób blokować podpowiedzi:\n   #b Zachowanie kursora myszy#! – Blokada podpowiedzi następuje po przesunięciu kursora myszy w jej kierunku.\n   #b Blokada względem czasu#! – Podpowiedź zostaje zablokowana po upływie określonego czasu.\n   #b Blokada względem działania#! – Blokada następuje po naciśnięciu środkowego przycisku myszy.\n   #b Blokada względem czasu lub działania#! – Podpowiedź można zablokować, korzystając z blokady względem czasu lub blokady względem działania."
 SETTING_TOOLTIP_MODE_NO_LOCK: "Brak blokady"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Zachowanie kursora myszy"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Blokada względem działania (zakotwiczenie myszy)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Blokada względem czasu (zakotwiczenie myszy)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Blokada względem działania"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Blokada względem czasu"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Blokada względem czasu lub działania"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nOkreśla opóźnienie, z jakim wyświetla się podpowiedź po wskazaniu elementu kursorem myszy."
 SETTING_TOOLTIP_DELAY: "Opóźnienie wyświetlenia"
 SETTING_TOOLTIP_UNLOCK_TIME: "Opóźnienie odblokowania"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nUstawia opóźnienie przed odblokowaniem podpowiedzi."
 SETTING_TOOLTIP_LOCK_TIME: "Opóźnienie zablokowania"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nUstawia opóźnienie przed zablokowaniem podpowiedzi."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Opóźnienie zablokowania (otwarta podpowiedź)"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nUstawia opóźnienie przed zablokowaniem podpowiedzi, kiedy inna podpowiedź jest już otwarta."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Zaawansowane"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Ogólne"
 SETTINGS_CATEGORY_SFX: "Efekty dźwiękowe"
 SETTINGS_CATEGORY_MFX: "Muzyka"
 SETTINGS_CATEGORY_LANGUAGE: "Język"
 SETTINGS_CATEGORY_SAVE_GAMES: "Zapisy gry"
 SETTINGS_CATEGORY_TOOLTIPS: "Ustawienia podpowiedzi"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Sterowanie na mapie"
 SETTINGS_CATEGORY_MAPMODES: "Tryby mapy"
 SETTING_SHADER_QUALITY: "Jakość shaderów"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Jakość shaderów\n#!Określa jakość różnorakich shaderów i efektów.\n\n#T Wysoka:#! poprawia jakość niektórych efektów shaderów kosztem wydajności.\n\n#T Średnia:#! domyślne ustawienie grafiki.\n\n#T Niska:#! ustawienie przeznaczone dla maszyn o niższej wydajności – nie jest zalecane ze względu na pogorszenie jakości obrazu. Aby zwiększyć wydajność grafiki, wiele shaderów zostaje uproszczonych."
 SETTING_SHOW_NUDITY: "Pokazuj nagość"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nOkreśla, czy postacie mogą być pokazywane nago."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portrety"
 SETTING_SOUNDTRACK: "Muzyka w tle"
 SETTING_SOUNDTRACK_TOOLTIP: "Ogólna muzyka w tle"
 SETTING_MUSIC_STINGERS: "Efekty muzyczne"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Krótkie muzyczne frazy urozmaicające rozgrywkę"
 #Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Muzyka"
 SETTING_AMBIENT: "Dźwięki otoczenia"
 SETTING_MUSIC_TOOLTIP: "#T Głośność muzyki\n#!Ustawienie to wpływa na głośność muzyki."
 SETTING_AMBIENT_TOOLTIP: "#T Głośność dźwięków otoczenia\n#!Ustawienie to wpływa na głośność dźwięków otoczenia."
 SETTING_MAP_TOOLTIP_DELAY: "Opóźnienie wyświetlania podpowiedzi na mapie"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nUstawia opóźnienie przed wyświetleniem podpowiedzi na mapie."
 SETTING_MAP_MODE_DELAY: "Opóźnienie trybu mapy"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Wyrażony w sekundach czas opóźnienia przed przełączeniem się na nowy tryb mapy"
 SETTING_MAP_MODE_FADE_IN: "Wyświetlenie trybu mapy"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Wyrażony w sekundach czas wygaszenia poprzedniego trybu mapy i wyświetlenia mapy w nowym trybie"
 SETTING_MAP_MODE_FADE_OUT: "Wygaszenie trybu mapy"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Wyrażony w sekundach czas wygaszenia mapy w bieżącym trybie (po upływie czasu opóźnienia trybu mapy), gdy ma zostać zastosowany nowy tryb mapy"
 SETTING_OCCUPATION_STRIPES: "Efekty wizualne okupacji – paski"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nSprawia, że w przypadku okupowanych państw na mapie zamiast flag widoczne są kolorowe paski."
 color_blind_mode_test: "Testuj"
