l_polish:
 SETTING_AUTOSAVE_TO_CLOUD:0 "Automatyczny zapis w chmurze"
 SETTING_SAVE_FILE_FORMAT:0 "Domyślny format zapisu"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "Ta opcja nie jest wykorzystywana w trybie Ironman, w trybie zapisu w chmurze oraz w trybie debugowania"
 OPTION_SAVE_FILE_TEXT:0 "Plik tekstowy"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Skompresowany plik tekstowy"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Skompresowany plik binarny"
 SETTING_TOOLTIP_MODE:0 "Tryb podpowiedzi"
 SETTING_TOOLTIP_MODE_TOOLTIP:1 "#T $SETTING_TOOLTIP_MODE$#!\nZdecyduj, w jaki sposób blokować podpowiedzi:\n   #b Zachowanie kursora myszy#! – Blokada podpowiedzi następuje po przesunięciu kursora myszy w jej kierunku.\n   #b Blokada względem czasu#! – Podpowiedź zostaje zablokowana po upływie określonego czasu.\n   #b Blokada względem działania#! – Blokada następuje po naciśnięciu środkowego przycisku myszy."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "Brak blokady"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Zachowanie kursora myszy"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Blokada względem działania (zakotwiczenie myszy)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Blokada względem czasu (zakotwiczenie myszy)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Blokada względem działania"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Blokada względem czasu"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nOkreśla opóźnienie, z jakim wyświetla się podpowiedź po wskazaniu elementu kursorem myszy."
 SETTING_TOOLTIP_DELAY:0 "Opóźnienie wyświetlenia"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Opóźnienie odblokowania"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nUstawia opóźnienie przed odblokowaniem podpowiedzi."
 SETTING_TOOLTIP_LOCK_TIME:0 "Opóźnienie zablokowania"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nUstawia opóźnienie przed zablokowaniem podpowiedzi."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Opóźnienie zablokowania (otwarta podpowiedź)"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nUstawia opóźnienie przed zablokowaniem podpowiedzi, kiedy inna podpowiedź jest już otwarta."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Zaawansowane"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Ogólne"
 SETTINGS_CATEGORY_SFX:0 "Określone efekty dźwiękowe"
 SETTINGS_CATEGORY_LANGUAGE:0 "Język"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Zapisy gry"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Ustawienia podpowiedzi"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Sterowanie na mapie"
 SETTING_SHADER_QUALITY:0 "Jakość shaderów"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Jakość shaderów\n#!Określa jakość różnorakich shaderów i efektów.\n\n#T Wysoka:#! poprawia jakość niektórych efektów shaderów kosztem wydajności.\n\n#T Średnia:#! domyślne ustawienie grafiki.\n\n#T Niska:#! ustawienie przeznaczone dla maszyn o niższej wydajności – nie jest zalecane ze względu na pogorszenie jakości obrazu. Aby zwiększyć wydajność grafiki, wiele shaderów zostaje uproszczonych."
 SETTING_SHOW_NUDITY:0 "Pokazuj nagość"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nOkreśla, czy postacie mogą być pokazywane nago."
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portrety"
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "Muzyka"
 SETTING_AMBIENT:0 "Dźwięki otoczenia"
 SETTING_MUSIC_TOOLTIP:0 "#T Głośność muzyki\n#!Ustawienie to wpływa na głośność muzyki."
 SETTING_AMBIENT_TOOLTIP:0 "#T Głośność dźwięków otoczenia\n#!Ustawienie to wpływa na głośność dźwięków otoczenia."

 color_blind_mode_test:0 "Testuj"
