l_russian:
 SETTING_INPUT_CONTEXT_COMMON: "Стандартные"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "Горячие клавиши для стандартных элементов управления"
 SETTING_INPUT_ACTION_PAUSE: "Пауза / Возобновить"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "Повысить скорость"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "Снизить скорость"
 SETTING_INPUT_ACTION_SPEED_ONE: "Скорость 1"
 SETTING_INPUT_ACTION_SPEED_TWO: "Скорость 2"
 SETTING_INPUT_ACTION_SPEED_THREE: "Скорость 3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "Скорость 4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "Скорость 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Пауза/Воспроизведение музыки"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Следующая композиция"
 SETTING_INPUT_ACTION_CAMERA_UP: "Камера вверх"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "Камера влево"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "Камера вниз"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "Камера вправо"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Поиск локаций"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Политика"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Бюджет"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Сооружения"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Рынок"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Вооружённые силы"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Дипломатия"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Технологии"
 SETTING_INPUT_ACTION_OPEN_SOCIETY: "Общество"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "Население"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Дневник"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Блок государств"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Компании"
 SETTING_INPUT_ACTION_MAP_LIST: "Летопись"
 SETTING_INPUT_ACTION_BACK: "Назад"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Планировщик"
 SETTING_INPUT_ACTION_TAB_1: "Вкладка 1"
 SETTING_INPUT_ACTION_TAB_2: "Вкладка 2"
 SETTING_INPUT_ACTION_TAB_3: "Вкладка 3"
 SETTING_INPUT_ACTION_TAB_4: "Вкладка 4"
 SETTING_INPUT_ACTION_TAB_5: "Вкладка 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Линза производства"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Линза политики"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Линза дипломатии"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Линза армии"
 SETTING_INPUT_ACTION_TRADE_LENS: "Линза торговли"
 SETTING_INPUT_ACTION_CONFIRM: "Подтвердить"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Текущая ситуация"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "Очередь строительства"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "Остановить/Возобновить очередь строительства"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Открыть сведения"
 SETTING_INPUT_ACTION_SCROLL_UP: "Вверх"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Вниз"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Debug) gui.debug"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "Показать закреплённое в планировщике"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "Показать экономику в планировщике"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "Показать политику в планировщике"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "Показать дипломатию в планировщике"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "Показать вооружённые силы в планировщике"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "Показать всё в планировщике"
 SETTING_INPUT_ACTION_TOGGLE_PIN: "Закрепить/Открепить"
 SETTING_INPUT_ACTION_ZOOM_TO: "Приблизить"
