l_russian:
 SETTING_AUTOSAVE_TO_CLOUD:0 "Автоматическое сохранение в облаке"
 SETTING_SAVE_FILE_FORMAT:0 "Стандартный формат сохранения"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "Этот вариант переписывается в режиме «Железная воля», облачном режиме и режиме отладки"
 OPTION_SAVE_FILE_TEXT:0 "Текст"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Сжатый текст"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Сжатый двоичный код"
 SETTING_TOOLTIP_MODE:0 "Режим всплывающих подсказок"
 SETTING_TOOLTIP_MODE_TOOLTIP:1 "#T $SETTING_TOOLTIP_MODE$#!\nВыберите метод закрепления подсказки:\n   #b Поведение мыши#! - Закрепляет при движении курсора в сторону подсказки.\n   #b Блок по таймеру#! - Закрепляет через определённое время.\n   #b Ручной блок#! - Закрепляется при нажатии средней кнопки мыши."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "Без закрепления"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Поведение мыши"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Ручной блок ( закрепление мышью )"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Блок по таймеру ( закрепление мышью )"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Ручной блок"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Блок по таймеру"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nУстанавливает задержку перед появлением всплывающей подсказки при наведении на соответствующий элемент."
 SETTING_TOOLTIP_DELAY:0 "Показать задержку"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Задержка разблокировки"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nЗадержка перед разблокировкой всплывающих подсказок."
 SETTING_TOOLTIP_LOCK_TIME:0 "Задержка блокировки"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nЗадержка перед блокировкой всплывающих подсказок."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Задержка открытия"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nЗадержка перед блокировкой всплывающих подсказок, если одна подсказка уже открыта."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Расширенные"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Общие"
 SETTINGS_CATEGORY_SFX:1 "Звуковые эффекты"
 SETTINGS_CATEGORY_MFX:0 "Музыка"
 SETTINGS_CATEGORY_LANGUAGE:0 "Язык"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Сохранение игры"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Настройки подсказок"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Управление картой"
 SETTINGS_CATEGORY_MAPMODES:0 "Режимы карты"
 SETTING_SHADER_QUALITY:0 "Качество шейдеров"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Качество шейдеров\n#!Определяет качество шейдеров и эффектов.\n\n#T Высокое:#! Повышает качество ряда эффектов шейдеров ценой снижения производительности.\n\n#T Среднее:#! Стандартные настройки для внешнего вида игры по задумке разработчиков.\n\n#T Низкое:#! Этот вариант предназначен для слабых машин. Мы не рекомендуем использовать его из-за падения качества графики. Многие шейдеры упрощены ради повышения производительности."
 SETTING_SHOW_NUDITY:0 "Показывать наготу"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nИзображение обнажённых персонажей."
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Портреты"
 SETTING_SOUNDTRACK:0 "Фоновая музыка"
 SETTING_SOUNDTRACK_TOOLTIP:0 "Общая фоновая музыка"
 SETTING_MUSIC_STINGERS:0 "Музыкальные всплески"
 SETTING_MUSIC_STINGERS_TOOLTIP:0 "Короткие музыкальные отрезки, призванные разнообразить игровой процесс"
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "Музыка"
 SETTING_AMBIENT:0 "Звуковое сопровождение"
 SETTING_MUSIC_TOOLTIP:0 "#T Громкость музыки\n#!Задаёт громкость музыки."
 SETTING_AMBIENT_TOOLTIP:0 "#T Звуковое сопровождение\n#!Задаёт громкость звукового сопровождения."
 
 SETTING_MAP_TOOLTIP_DELAY:0 "Задержка подсказки на карте"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nУстанавливает задержку перед появлением всплывающей подсказки на карте."
 
 SETTING_MAP_MODE_DELAY:0 "Задержка смены режима карты"
 SETTING_MAP_MODE_DELAY_TOOLTIP:0 "Задержка перед переключением в другой режим карты (в секундах)"
 SETTING_MAP_MODE_FADE_IN:0 "Появление режима карты"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP:0 "Время на появление нового режима карты после исчезновения предыдущего (в секундах)"
 SETTING_MAP_MODE_FADE_OUT:0 "Исчезновение режима карты"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP:0 "Время на исчезновение текущего режима карты по истечении периода задержки перед переключением в другой режим (в секундах)"

 color_blind_mode_test:0 "Тест"
