l_braz_por:
 SETTING_INPUT_CONTEXT_COMMON: "Comum"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "Atalhos do teclado para o contexto de comando comum"
 SETTING_INPUT_ACTION_PAUSE: "Pausar / Retomar"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "Aumentar Velocidade"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "Diminuir Velocidade"
 SETTING_INPUT_ACTION_SPEED_ONE: "Velocidade 1"
 SETTING_INPUT_ACTION_SPEED_TWO: "Velocidade 2"
 SETTING_INPUT_ACTION_SPEED_THREE: "Velocidade 3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "Velocidade 4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "Velocidade 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Reproduzir/Pausar Música"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Próxima Faixa Musical"
 SETTING_INPUT_ACTION_CAMERA_UP: "Mover a câmera para cima"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "Mover a câmera para a esquerda"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "Mover a câmera para baixo"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "Mover a câmera para a direita"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Buscador de Local"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Política"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Orçamento"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Construções"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Mercado"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Militares"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Diplomático"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Tecnologia"
 SETTING_INPUT_ACTION_OPEN_CULTURE: "Cultura"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "População"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Diário"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Bloco de Poder"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Companhias"
 SETTING_INPUT_ACTION_MAP_LIST: "Livro-razão"
 SETTING_INPUT_ACTION_BACK: "Voltar"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Destaques"
 SETTING_INPUT_ACTION_TAB_1: "Aba 1"
 SETTING_INPUT_ACTION_TAB_2: "Aba 2"
 SETTING_INPUT_ACTION_TAB_3: "Aba 3"
 SETTING_INPUT_ACTION_TAB_4: "Aba 4"
 SETTING_INPUT_ACTION_TAB_5: "Aba 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Olhar Produtivo"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Olhar Político"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Olhar Diplomático"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Olhar Militar"
 SETTING_INPUT_ACTION_TRADE_LENS: "Olhar Comercial"
 SETTING_INPUT_ACTION_CONFIRM: "Confirmar"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Situação Atual"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "Fila de Obras"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "Pausar/Retomar Fila de Obras"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Ir para Detalhes"
 SETTING_INPUT_ACTION_SCROLL_UP: "Rolar para cima"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Rolar para baixo"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Debug) gui.debug"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "Mostrar Fixados nos Destaques"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "Mostrar Economia nos Destaques"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "Mostrar Política nos Destaques"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "Mostrar Diplomacia nos Destaques"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "Mostrar Militares nos Destaques"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "Mostrar Tudo nos Destaques"
 SETTING_INPUT_ACTION_TOGGLE_PIN: "Alternar Fixação"
 SETTING_INPUT_ACTION_ZOOM_TO: "Aproximar para"
