l_braz_por:
 SETTING_AUTOSAVE_TO_CLOUD: "Salvamento automático na nuvem"
 SETTING_SAVE_FILE_FORMAT: "Formato de salvamento padrão"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Esta opção é anulada nos modos Ironman, Nuvem e Debug"
 OPTION_SAVE_FILE_TEXT: "Texto"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Texto compactado"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Binário compactado"
 SETTING_TOOLTIP_MODE: "Modo Dicas de Contexto"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nEscolha como as dicas de contexto devem ficar travadas:\n   #b Tendência do Mouse#! - Trava se o mouse for movido em direção à dica de contexto.\n   #b Travamento por Tempo#! - Trava após um tempo predeterminado.\n   #b Travamento por Ação#! - Trava com o botão do meio do mouse.\n   #b Travamento por Tempo ou Ação#! - Pode usar Travamento por Tempo ou por Ação."
 SETTING_TOOLTIP_MODE_NO_LOCK: "Sem bloqueio"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Tendência do Mouse"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Travamento por Ação (Ancoragem do Mouse)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Travamento por Tempo (Ancoragem do Mouse)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Travamento por Ação"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Travamento por Tempo"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Travamento por Tempo ou Ação"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nDefine o atraso antes da dica de contexto aparecer, ao passar o cursor sobre um elemento com dica de contexto."
 SETTING_TOOLTIP_DELAY: "Mostrar Atraso"
 SETTING_TOOLTIP_UNLOCK_TIME: "Desbloquear Atraso"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nDefine o atraso até as dicas de contexto serem desbloqueadas."
 SETTING_TOOLTIP_LOCK_TIME: "Bloquear Atraso"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nDefine o atraso até as dicas de contexto serem bloqueadas."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Atraso Aberto Bloqueado"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nDefine o atraso até as dicas de contexto serem bloqueadas quando outras já estão abertas."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Avançado"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Geral"
 SETTINGS_CATEGORY_SFX: "Efeitos Sonoros"
 SETTINGS_CATEGORY_MFX: "Música"
 SETTINGS_CATEGORY_LANGUAGE: "Idioma"
 SETTINGS_CATEGORY_SAVE_GAMES: "Jogos Salvos"
 SETTINGS_CATEGORY_TOOLTIPS: "Configuração das Dicas de Contexto"
 SETTINGS_CATEGORY_OUTLINER: "Destaques"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Controles do Mapa"
 SETTINGS_CATEGORY_MAPMODES: "Modos de Mapa"
 SETTING_SHADER_QUALITY: "Qualidade de Sombreamento"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Qualidade de Sombreamento\n#!Determina a qualidade de diversos efeitos e do sombreamento.\n\n#T Alta:#! melhora a qualidade de alguns efeitos de sombreamento em detrimento do desempenho.\n\n#T Média:#! configuração padrão para a experiência gráfica pretendida.\n\n#T Baixa:#! configuração destinada a máquinas de baixo desempenho e não recomendada devido à perda de qualidade gráfica. Diversos sombreamentos são simplificados para impulsionar o desempenho."
 SETTING_SHOW_NUDITY: "Mostrar nudez"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nDefine se os personagens podem aparecer nus."
 SETTING_VALUE_HOURS: "$VALUE|0$ Horas"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "Ciclo dia e noite"
 SETTING_DAYNIGHT_CYCLE: "Ativar o ciclo de dia e noite"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\nAtiva um ciclo dia e noite para o movimento do Sol."
 SETTING_DAYNIGHT_SYSTEMTIME: "Ativar sincronização com a hora local"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nSincroniza a velocidade e a hora do ciclo dia e noite com a hora local do computador.\n\n#!Isso substituirá a configuração de velocidade da simulação."
 SETTING_DAYNIGHT_SPEED: "Velocidade da Simulação"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\nA velocidade com que o tempo passa no ciclo dia e noite.#!"
 SETTING_SUN_DURATION: "Horas diurnas"
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\nA quantidade de horas de sol em um dia."
 SETTING_SUNRISE_TIME: "Hora do nascer do sol"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\nA hora que o sol nasce.\n\n#!Apenas com sincronização com a hora local.#!"
 SETTING_DAYNIGHT_SET_TIME: "Ativar horário manual"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\nDefine uma hora do dia específica.\n\n#!Isso substituirá as configurações de velocidade da simulação e de sincronização com a hora local."
 SETTING_SUNRISE_SET_TIME_HOUR: "Hora manual"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nDefine esta hora.\n\n#!Apenas quando o horário manual estiver ativado.#!"
 SETTING_BUILDINGS_CUTOFF: "Omitir Construções Distantes"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP: "#T $SETTING_BUILDINGS_CUTOFF$#!\nMostrar menos construções no mapa conforme a câmera se afasta delas.\n\nOptar por isso pode aumentar o desempenho."
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER: "Notificações à esquerda dos Destaques"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER_TOOLTIP: "#t $SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER$#!\nPosicionar as Notificações à esquerda dos Destaques"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Retratos"
 SETTING_SOUNDTRACK: "Música de Fundo"
 SETTING_SOUNDTRACK_TOOLTIP: "Música de fundo geral"
 SETTING_MUSIC_STINGERS: "Sinais Musicais"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Frases musicais curtas para melhorar a jogabilidade"
 #Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Música"
 SETTING_AMBIENT: "Ambiente"
 SETTING_MUSIC_TOOLTIP: "#T Volume da Música\n#!Define o volume da música."
 SETTING_AMBIENT_TOOLTIP: "#T Volume Ambiente\n#!Define o volume do som ambiente."
 SETTING_MAP_TOOLTIP_DELAY: "Atraso da Dica de Contexto do Mapa"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nDefine o atraso até a dica de contexto do mapa ser mostrada."
 SETTING_MAP_MODE_DELAY: "Atraso do Modo de Mapa"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "O atraso em segundos antes de trocar para um novo Modo de Mapa"
 SETTING_MAP_MODE_FADE_IN: "Aparecimento do Modo de Mapa"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Tempo em segundos para que um novo Modo de Mapa apareça, após o desaparecimento do anterior"
 SETTING_MAP_MODE_FADE_OUT: "Desaparecimento do Modo de Mapa"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Tempo em segundos para que o Modo de Mapa atual desapareça, após o Atraso do Modo de Mapa, quando um novo é aplicado"
 SETTING_OCCUPATION_STRIPES: "Visuais Listrados das Ocupações"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nAtivar listras coloridas como visuais das ocupações no mapa em vez das texturas de bandeira do país"
 SETTING_PORTRAIT_RENDER_SCALE: "Dimensionamento de Renderização de Retrato"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\nMelhora o nível de detalhes dos retratos de personagens, dimensionando os resultados da renderização às custas de mais desempenho da renderização."
 OPTION_PORTRAIT_RENDER_SCALE_NONE: "×1,0 - Nenhum"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "×1,5 - Médio"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "×2,0 - Alto"
 ui_skin_theme: "Interface de Usuário"
 ui_skin_theme_desc: "Botões, quadros, janelas, cabeçalhos e outros elementos do jogo."
 papermap_theme: "Mapa de Papel"
 papermap_theme_desc: "Este é o mapa que você vê ao afastar a câmera."
 table_top_theme: "Mesa"
 table_top_theme_desc: "Se afastar a câmera o máximo possível do mapa, você verá esta mesa na parte superior e na parte inferior da tela."
 table_asset_1_theme: "Objeto da Mesa (canto superior esquerdo)"
 table_asset_1_theme_desc: "O objeto exibido no canto superior esquerdo da mesa, próximo ao mapa, ao afastar a câmera."
 table_asset_2_theme: "Objeto da Mesa (canto superior direito)"
 table_asset_2_theme_desc: "O objeto exibido no canto superior direito da mesa, próximo ao mapa, ao afastar a câmera."
 table_asset_3_theme: "Objeto da Mesa (canto inferior esquerdo)"
 table_asset_3_theme_desc: "O objeto exibido no canto inferior esquerdo da mesa, próximo ao mapa, ao afastar a câmera."
 table_asset_4_theme: "Objeto da Mesa (canto inferior direito)"
 table_asset_4_theme_desc: "O objeto exibido no canto inferior direito da mesa, próximo ao mapa, ao afastar a câmera."
 building_sets_themes: "Cenário da Construção"
 color_blind_mode_test: "Testar"
