l_turkish:
 SETTING_AUTOSAVE_TO_CLOUD:0 "Buluta otomatik kaydet"
 SETTING_SAVE_FILE_FORMAT:0 "Varsayılan kayıt biçimi"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP:0 "Bu seçenek Tek Şans, Bulut ve Hata Ayıklama modlarında geçersiz kılınmıştır"
 OPTION_SAVE_FILE_TEXT:0 "Metin"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL:0 "Sıkıştırılmış metin"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL:0 "Sıkıştırılmış ikili değer"
 SETTING_TOOLTIP_MODE:0 "Bilgi Kutusu Modu"
 SETTING_TOOLTIP_MODE_TOOLTIP:1 "#T $SETTING_TOOLTIP_MODE$#!\nBilgi kutularının nasıl kilitleneceğini seç:\n   #b Fare Hassasiyeti#! - Fareni bilgi kutusuna doğru hareket ettirdiğinde kilitler.\n   #b Zamanlayıcı Kilidi#! - Belirli bir süreden sonra kilitler.\n   #b Eylem Kilidi#! - Fare tekerleğine basmayla kilitler."
 SETTING_TOOLTIP_MODE_NO_LOCK:0 "Kilitsiz"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Fare Hassasiyeti"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR:0 "Eylem Kilidi (Fare Sabitleme)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR:0 "Zamanlayıcı Kilidi (Fare Sabitleme)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR:0 "Eylem Kilidi"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR:0 "Zamanlayıcı Kilidi"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nİmleci bilgi kutusu olan bir unsurun üzerine getirdiğinde bilgi kutusunun görünme gecikmesini belirler."
 SETTING_TOOLTIP_DELAY:0 "Gecikmeyi Göster"
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Kilit Açma Gecikmesi"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nBilgi kutusu kilidinin açılma gecikmesini belirler."
 SETTING_TOOLTIP_LOCK_TIME:0 "Kilitleme Gecikmesi"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:0 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nBilgi kutularının kilitlenme gecikmesini belirler."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Açıkken Kilitleme Gecikmesi"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:0 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nBaşka bir bilgi kutusu açıkken diğer bilgi kutularının kilitlenme gecikmesini belirler."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Gelişmiş"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Genel"
 SETTINGS_CATEGORY_SFX:1 "Ses Efektleri"
 SETTINGS_CATEGORY_MFX:0 "Müzik"
 SETTINGS_CATEGORY_LANGUAGE:0 "Dil"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Kayıtlı Oyunlar"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Bilgi Kutusu Ayarları"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Harita Kontrolleri"
 SETTING_SHADER_QUALITY:0 "Gölgelendirici Kalitesi"
 SETTING_SHADER_QUALITY_TOOLTIP:1 "#T Gölgelendirici Kalitesi\n#!Çeşitli gölgelendiricilerin ve efektlerin kalitesini belirler.\n\n#T Yüksek:#! Performanstan ödün vererek bazı gölgelendirici efektlerinin kalitesini yükseltir.\n\n#T Orta:#! İdeal görsel deneyim için varsayılan ayar.\n\n#T Düşük:#! Bu ayar, düşük seviye cihazlar için tasarlanmıştır ve görsel kalitede kayba neden olduğundan önerilmez. Grafik performansını arttırmak için birçok gölgelendirici efekti basitleştirilir."
 SETTING_SHOW_NUDITY:0 "Çıplaklık göster"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nKarakterlerin çıplak gösterilip gösterilemeyeceğini belirler."
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portreler"
 SETTING_SOUNDTRACK:0 "Arka Plan Müziği"
 SETTING_SOUNDTRACK_TOOLTIP:0 "Genel arka plan müziği"
 SETTING_MUSIC_STINGERS:0 "Müzikli Geçişler"
 SETTING_MUSIC_STINGERS_TOOLTIP:0 "Oynanışı geliştirmek için çalınan kısa müzik geçişleri"
  # Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC:0 "Müzik"
 SETTING_AMBIENT:0 "Ambiyans"
 SETTING_MUSIC_TOOLTIP:0 "#T Müzik Düzeyi\n#!Çalan müziklerin ses düzeyini belirler."
 SETTING_AMBIENT_TOOLTIP:0 "#T Ortam Sesleri Düzeyi\n#!Çevresel ambiyans seslerinin düzeyini belirler."
 
 SETTING_MAP_TOOLTIP_DELAY:0 "Harita Bilgi Kutusu Gecikmesi"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP:0 "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nHarita bilgi kutusunun gösterilme gecikmesini belirler."

 color_blind_mode_test:0 "Test"
