l_turkish:
 SETTING_AUTOSAVE_TO_CLOUD: "Buluta otomatik kaydet"
 SETTING_SAVE_FILE_FORMAT: "Varsayılan kayıt biçimi"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Bu seçenek Tek Şans, Bulut ve Hata Ayıklama modlarında geçersiz kılınmıştır"
 OPTION_SAVE_FILE_TEXT: "Metin"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Sıkıştırılmış metin"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Sıkıştırılmış ikili değer"
 SETTING_TOOLTIP_MODE: "Bilgi Kutusu Modu"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nBilgi kutularının nasıl kilitleneceğini seç:\n   #b Fare Hassasiyeti#! - Fareni bilgi kutusuna doğru hareket ettirdiğinde kilitler.\n   #b Zamanlayıcı Kilidi#! - Belirli bir süreden sonra kilitler.\n   #b Eylem Kilidi#! - Fare tekerleğine basmayla kilitler.\n   #b Zamanlayıcı veya Eylem Kilidi#! - Zamanlayıcı Kilidi veya Eylem Kilidi kullanılabilir."
 SETTING_TOOLTIP_MODE_NO_LOCK: "Kilitsiz"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Fare Hassasiyeti"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Eylem Kilidi (Fare Sabitleme)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Zamanlayıcı Kilidi (Fare Sabitleme)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Eylem Kilidi"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Zamanlayıcı Kilidi"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Zamanlayıcı veya Eylem Kilidi"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nİmleci bilgi kutusu olan bir unsurun üzerine getirdiğinde bilgi kutusunun görünme gecikmesini belirler."
 SETTING_TOOLTIP_DELAY: "Gecikmeyi Göster"
 SETTING_TOOLTIP_UNLOCK_TIME: "Kilit Açma Gecikmesi"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nBilgi kutusu kilidinin açılma gecikmesini belirler."
 SETTING_TOOLTIP_LOCK_TIME: "Kilitleme Gecikmesi"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nBilgi kutularının kilitlenme gecikmesini belirler."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Açıkken Kilitleme Gecikmesi"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nBaşka bir bilgi kutusu açıkken diğer bilgi kutularının kilitlenme gecikmesini belirler."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Gelişmiş"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Genel"
 SETTINGS_CATEGORY_SFX: "Ses Efektleri"
 SETTINGS_CATEGORY_MFX: "Müzik"
 SETTINGS_CATEGORY_LANGUAGE: "Dil"
 SETTINGS_CATEGORY_SAVE_GAMES: "Kayıtlı Oyunlar"
 SETTINGS_CATEGORY_TOOLTIPS: "Bilgi Kutusu Ayarları"
 SETTINGS_CATEGORY_OUTLINER: "Yan Bilgi"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Harita Kontrolleri"
 SETTINGS_CATEGORY_MAPMODES: "Harita Modları"
 SETTING_SHADER_QUALITY: "Gölgelendirici Kalitesi"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Gölgelendirici Kalitesi\n#!Çeşitli gölgelendiricilerin ve efektlerin kalitesini belirler.\n\n#T Yüksek:#! Performanstan ödün vererek bazı gölgelendirici efektlerinin kalitesini yükseltir.\n\n#T Orta:#! İdeal görsel deneyim için varsayılan ayar.\n\n#T Düşük:#! Bu ayar, düşük seviye cihazlar için tasarlanmıştır ve görsel kalitede kayba neden olduğundan önerilmez. Grafik performansını arttırmak için birçok gölgelendirici efekti basitleştirilir."
 SETTING_SHOW_NUDITY: "Çıplaklık göster"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nKarakterlerin çıplak gösterilip gösterilemeyeceğini belirler."
 SETTING_VALUE_HOURS: "$VALUE|0$ Saat"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$.00"
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "Gece gündüz döngüsü"
 SETTING_DAYNIGHT_CYCLE: "Gece gündüz döngüsünü etkinleştir"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\nGüneşin hareket ederek bir gece gündüz döngüsü oluşturmasını sağlar."
 SETTING_DAYNIGHT_SYSTEMTIME: "Yerel saati senkronize etmeyi etkinleştir"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nGece gündüz döngüsünün hızını ve saatini bilgisayarın yerel saatiyle senkronize eder.\n\n#!Simülasyon hızı ayarını geçersiz kılar."
 SETTING_DAYNIGHT_SPEED: "Simülasyon Hızı"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\nZamanın gece ve gündüz arasında ne kadar hızlı akacağını belirler."
 SETTING_SUN_DURATION: "Gündüz saatleri"
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\nGüneşin etkin kalacağı saatleri belirler."
 SETTING_SUNRISE_TIME: "Gündoğumu vakti"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\nGüneşin doğacağı vakit.\n\n#!Yalnızca yerel saatle senkronize olunca kullanılır. #!"
 SETTING_DAYNIGHT_SET_TIME: "Manuel zamanı etkinleştir"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\nGünün vaktini belli bir saate ayarlar.\n\n#!Simülasyon hızı ve yerel saat senkronizasyonu ayarlarını geçersiz kılar."
 SETTING_SUNRISE_SET_TIME_HOUR: "Manuel saat"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nZamanı bu saatte kilitli tutar.\n\n#!Yalnızca manuel zaman ayarı etkinken kullanılır."
 SETTING_BUILDINGS_CUTOFF: "Uzaktaki Binaları Gösterme"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP: "#T $SETTING_BUILDINGS_CUTOFF$#!\nKamera mesafesi arttıkça haritada daha az sayıda bina gösterilir.\n\nBu ayarı açmak performansı arttırabilir."
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER: "Bildirimler yan bilgilerin sol tarafında görünsün"
 SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER_TOOLTIP: "#t $SETTING_SHOW_NOTIFICATION_FEED_NEXT_TO_OUTLINER$#!\nBildirim akışını yan bilgi panelinin soluna yerleştir."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portreler"
 SETTING_SOUNDTRACK: "Arka Plan Müziği"
 SETTING_SOUNDTRACK_TOOLTIP: "Genel arka plan müziği"
 SETTING_MUSIC_STINGERS: "Müzikli Geçişler"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Oynanışı geliştirmek için çalınan kısa müzik geçişleri"
 #Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Müzik"
 SETTING_AMBIENT: "Ambiyans"
 SETTING_MUSIC_TOOLTIP: "#T Müzik Düzeyi\n#!Çalan müziklerin ses düzeyini belirler."
 SETTING_AMBIENT_TOOLTIP: "#T Ortam Sesleri Düzeyi\n#!Çevresel ambiyans seslerinin düzeyini belirler."
 SETTING_MAP_TOOLTIP_DELAY: "Harita Bilgi Kutusu Gecikmesi"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nHarita bilgi kutusunun gösterilme gecikmesini belirler."
 SETTING_MAP_MODE_DELAY: "Harita Modu Gecikmesi"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Yeni bir Harita Modu'na geçerken yaşanan saniye bazında gecikme."
 SETTING_MAP_MODE_FADE_IN: "Harita Modu'nun Görünmesi"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Eskisi kaybolduktan sonra yeni bir Harita Modu'nun saniye bazında ortaya çıkma süresi."
 SETTING_MAP_MODE_FADE_OUT: "Harita Modu'nun Kaybolması"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Harita Modu Gecikmesi'nden sonra yeni Harita Modu'nun uygulanması için mevcut Harita Modu'nun saniye bazında kaybolma süresi."
 SETTING_OCCUPATION_STRIPES: "Şeritli İşgal Görüntüleri"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nİşgal görüntüsü olarak ülke bayrağı dokuları yerine renkli şeritleri etkinleştir."
 SETTING_PORTRAIT_RENDER_SCALE: "Portre İşleme Ölçeklemesi"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\nİşleme sonuçlarını yukarı ölçekleyerek karakter portrelerinin ayrıntı düzeyini geliştirir. Daha fazla işleme performansı gerektirir."
 OPTION_PORTRAIT_RENDER_SCALE_NONE: "×1.0 - Yok"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "×1.5 - Orta"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "×2.0 - Yüksek"
 ui_skin_theme: "Kullanıcı Arayüzü"
 ui_skin_theme_desc: "Oyundaki butonlar, çerçeveler, pencereler, başlıklar ve benzeri unsurlar."
 papermap_theme: "Kâğıt Harita"
 papermap_theme_desc: "Uzaklaştığında bu haritayı görürsün."
 table_top_theme: "Masa Oyunu"
 table_top_theme_desc: "Haritayı olabildiğince uzaklaştırırsan ekranın alt ve üst kısımlarında bu masayı görebilirsin."
 table_asset_1_theme: "Masa Nesnesi (sol üst)"
 table_asset_1_theme_desc: "Uzaklaştığında masanın sol üst tarafında, haritanın yanında görüntülenecek nesne."
 table_asset_2_theme: "Masa Nesnesi (sağ üst)"
 table_asset_2_theme_desc: "Uzaklaştığında masanın sağ üst tarafında, haritanın yanında görüntülenecek nesne."
 table_asset_3_theme: "Masa Nesnesi (sol alt)"
 table_asset_3_theme_desc: "Uzaklaştığında masanın sol alt tarafında, haritanın yanında görüntülenecek nesne."
 table_asset_4_theme: "Masa Nesnesi (sağ alt)"
 table_asset_4_theme_desc: "Uzaklaştığında masanın sağ alt tarafında, haritanın yanında görüntülenecek nesne."
 building_sets_themes: "Bina Seti"
 color_blind_mode_test: "Test"
