l_french:
 SETTING_AUTOSAVE_TO_CLOUD: "Sauvegarde auto sur le Cloud"
 SETTING_SAVE_FILE_FORMAT: "Format de sauvegarde par défaut"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Cette option est ignorée en mode Ironman, Cloud et Debug"
 OPTION_SAVE_FILE_TEXT: "Texte"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Texte condensé"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Binaire condensé"
 SETTING_TOOLTIP_MODE: "Mode infobulle"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nComment les infobulles doivent se verrouiller ?\n   #b Selon la souris#! - se verrouille si vous déplacez la souris vers l’infobulle.\n   #b Selon le temps#! - se verrouille après un temps défini.\n   #b Selon l’action#! - se verrouille via le bouton central de la souris.\n   #b Selon le temps ou l’action#! - se verrouille soit selon le temps soit selon l’action."
 SETTING_TOOLTIP_MODE_NO_LOCK: "Pas de verrouillage"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Selon la souris"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Verrouillage de l’action (ancrage souris)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Verrouillage du temps (ancrage souris)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Selon l’action"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Selon le temps"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Selon le temps ou l’action"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nDéfinit le délai avant que l’infobulle n’apparaisse lors du survol d’un élément avec une infobulle."
 SETTING_TOOLTIP_DELAY: "Afficher le délai"
 SETTING_TOOLTIP_UNLOCK_TIME: "Délai de déverrouillage"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nDéfinit le délai avant le déverrouillage des infobulles."
 SETTING_TOOLTIP_LOCK_TIME: "Délai de verrouillage"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nDéfinit le délai avant le verrouillage des infobulles."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Délai de verrouillage si ouvert"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nDéfinit le délai avant le verrouillage des infobulles lorsqu’une autre infobulle est déjà ouverte."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Avancé"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Général"
 SETTINGS_CATEGORY_SFX: "Effets sonores"
 SETTINGS_CATEGORY_MFX: "Musique"
 SETTINGS_CATEGORY_LANGUAGE: "Langue"
 SETTINGS_CATEGORY_SAVE_GAMES: "Sauvegardes"
 SETTINGS_CATEGORY_TOOLTIPS: "Paramètres des infobulles"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Contrôles de carte"
 SETTINGS_CATEGORY_MAPMODES: "Modes de carte"
 SETTING_SHADER_QUALITY: "Qualité des nuanceurs"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Qualité des nuanceurs\n#!Permet de régler la qualité des différents effets et nuanceurs.\n\n#T Élevée :#! améliore la qualité des nuanceurs, mais réduit les performances.\n\n#T Moyenne :#! paramètres par défaut pour des graphismes optimaux.\n\n#T Faible :#! plusieurs nuanceurs sont simplifiés afin de réduire la qualité des graphismes et d’améliorer les performances pour les machines moins puissantes."
 SETTING_SHOW_NUDITY: "Afficher la nudité"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nDéfinit si les personnages peuvent être affichés nus."
 SETTING_VALUE_HOURS: "$VALUE|0$ heures"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "Cycle jour et nuit"
 SETTING_DAYNIGHT_CYCLE: "Activer le cycle jour et nuit"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\nPermet un cycle jour/nuit pour le mouvement du soleil."
 SETTING_DAYNIGHT_SYSTEMTIME: "Activer la synchronisation de l’heure locale"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nSynchronise la vitesse et l’heure du cycle jour-nuit avec l’heure locale de l’ordinateur.\n\nCela ignore le réglage de la vitesse de simulation."
 SETTING_DAYNIGHT_SPEED: "Vitesse de simulation"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\nLa vitesse à laquelle l’heure passe du jour à la nuit."
 SETTING_SUN_DURATION: "Heures de soleil"
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\nLe nombre d’heures de soleil par jour."
 SETTING_SUNRISE_TIME: "Heure du lever du soleil"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\nL’heure à laquelle le soleil se lève.\n\nUtilisé uniquement en cas de synchronisation avec l’heure locale."
 SETTING_DAYNIGHT_SET_TIME: "Activer l’heure manuelle"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\nRègle l’heure du jour à une heure spécifiée.\n\nIgnore les réglages de vitesse de simulation et de synchronisation de l’heure locale."
 SETTING_SUNRISE_SET_TIME_HOUR: "Heure manuelle"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nVerrouille l’heure choisie.\n\nUtilisé uniquement lorsque l’heure manuelle est activée."
 SETTING_BUILDINGS_CUTOFF: "Masquer les bâtiments distants"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP: "#T $SETTING_BUILDINGS_CUTOFF$#!\nAffiche moins de bâtiments sur la carte à mesure que la distance de la caméra augmente.\n\nActiver ceci peut améliorer les performances."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portraits"
 SETTING_SOUNDTRACK: "Musique de fond"
 SETTING_SOUNDTRACK_TOOLTIP: "Musique de fond générale"
 SETTING_MUSIC_STINGERS: "Phrases musicales"
 SETTING_MUSIC_STINGERS_TOOLTIP: "De courtes phrases musicales pour améliorer la jouabilité"
 #Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Musique"
 SETTING_AMBIENT: "Ambiance"
 SETTING_MUSIC_TOOLTIP: "#T Volume de la musique\n#!Permet de régler le volume de la musique."
 SETTING_AMBIENT_TOOLTIP: "#T Volume d’ambiance\n#!Permet de régler le volume des sons d’ambiance."
 SETTING_MAP_TOOLTIP_DELAY: "Délai de l’infobulle de la carte"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nDéfinit le délai avant l’affichage de l’infobulle de la carte."
 SETTING_MAP_MODE_DELAY: "Délai du mode carte"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Délai avant de passer à un autre mode de carte, en secondes."
 SETTING_MAP_MODE_FADE_IN: "Temps du nouveau mode de carte"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Temps pour qu’un nouveau mode de carte apparaisse après la disparition de l’ancien, en secondes."
 SETTING_MAP_MODE_FADE_OUT: "Temps de l’ancien mode de carte"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Temps nécessaire pour que le mode de carte actuel disparaisse lorsqu’un nouveau mode de carte doit être appliqué, en secondes."
 SETTING_OCCUPATION_STRIPES: "Bandes de couleur pour l’occupation"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nAfficher des bandes de couleur pour signaler l’occupation sur la carte plutôt que les textures de drapeau du pays"
 SETTING_PORTRAIT_RENDER_SCALE: "Mise à l’échelle du rendu du portrait"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\nAméliore le niveau de détail du portrait du personnage en augmentant l’échelle des résultats du rendu, au prix d’une petite perte des performances."
 OPTION_PORTRAIT_RENDER_SCALE_NONE: "×1,0 - Aucune"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "×1,5 - Moyenne"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "×2,0 - Élevée"
 ui_skin_theme: "Interface utilisateur"
 ui_skin_theme_desc: "Les boutons, cadres, fenêtres, en-têtes, etc. du jeu."
 papermap_theme: "Carte en papier"
 papermap_theme_desc: "C’est la carte que vous voyez lorsque vous faites un zoom arrière."
 table_top_theme: "Dessus de table"
 table_top_theme_desc: "Si vous effectuez un zoom arrière maximum sur la carte, vous pouvez voir cette table en haut et en bas de votre écran."
 table_asset_1_theme: "Objet de la table (en haut à gauche)"
 table_asset_1_theme_desc: "L’objet affiché en haut à gauche de la table à côté de la carte lorsque l’on fait un zoom arrière."
 table_asset_2_theme: "Objet de table (en haut à droite)"
 table_asset_2_theme_desc: "L’objet affiché en haut à droite de la table à côté de la carte lorsque l’on fait un zoom arrière."
 table_asset_3_theme: "Objet de la table (en bas à gauche)"
 table_asset_3_theme_desc: "L’objet affiché en bas à gauche de la table à côté de la carte lorsque l’on fait un zoom arrière."
 table_asset_4_theme: "Objet de la table (en bas à droite)"
 table_asset_4_theme_desc: "L’objet affiché en bas à droite de la table à côté de la carte lorsque l’on fait un zoom arrière."
 building_sets_themes: "Ensemble de bâtiments"
 color_blind_mode_test: "Test"
