l_german:
 SETTING_INPUT_CONTEXT_COMMON: "Üblich"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "Tastaturbelegungen für übliche Kontexteingaben"
 SETTING_INPUT_ACTION_PAUSE: "Pause / Beenden"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "Tempo erhöhen"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "Tempo senken"
 SETTING_INPUT_ACTION_SPEED_ONE: "Tempo 1"
 SETTING_INPUT_ACTION_SPEED_TWO: "Tempo 2"
 SETTING_INPUT_ACTION_SPEED_THREE: "Tempo 3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "Tempo 4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "Tempo 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Musik spielen/pausieren"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Nächster Musiktitel"
 SETTING_INPUT_ACTION_CAMERA_UP: "Kamera nach oben schwenken"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "Kamera nach links schwenken"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "Kamera nach unten schwenken"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "Kamera nach rechts schwenken"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Ortsfinder"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Politik"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Etat"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Gebäude"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Markt"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Militär"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Diplomatisch"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Technik"
 SETTING_INPUT_ACTION_OPEN_CULTURE: "Kultur"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "Bevölkerung"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Journal"
 SETTING_INPUT_ACTION_OPEN_DECISIONS: "Entscheidungen"
 SETTING_INPUT_ACTION_MAP_LIST: "Hauptbuch"
 SETTING_INPUT_ACTION_BACK: "Zurück"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Pinnwand"
 SETTING_INPUT_ACTION_TAB_1: "Reiter 1"
 SETTING_INPUT_ACTION_TAB_2: "Reiter 2"
 SETTING_INPUT_ACTION_TAB_3: "Reiter 3"
 SETTING_INPUT_ACTION_TAB_4: "Reiter 4"
 SETTING_INPUT_ACTION_TAB_5: "Reiter 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Produktionslinse"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Politiklinse"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Diplomatielinse"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Militärlinse"
 SETTING_INPUT_ACTION_TRADE_LENS: "Handelslinse"
 SETTING_INPUT_ACTION_CONFIRM: "Bestätigen"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Derzeitige Lage"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "Baureihe"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "Baureihe pausieren/wieder starten"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Zu Details gehen"
 SETTING_INPUT_ACTION_SCROLL_UP: "Nach oben scrollen"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Nach unten scrollen"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Debug) gui.debug"
