l_spanish:
 SETTING_INPUT_CONTEXT_COMMON: "Común"
 SETTING_INPUT_CONTEXT_COMMON_TOOLTIP: "Combinaciones de teclas para contexto de entrada común"
 SETTING_INPUT_ACTION_PAUSE: "Pausar/Reanudar"
 SETTING_INPUT_ACTION_INCREASE_SPEED: "Aumentar la velocidad"
 SETTING_INPUT_ACTION_DECREASE_SPEED: "Reducir la velocidad"
 SETTING_INPUT_ACTION_SPEED_ONE: "Velocidad 1"
 SETTING_INPUT_ACTION_SPEED_TWO: "Velocidad 2"
 SETTING_INPUT_ACTION_SPEED_THREE: "Velocidad 3"
 SETTING_INPUT_ACTION_SPEED_FOUR: "Velocidad 4"
 SETTING_INPUT_ACTION_SPEED_FIVE: "Velocidad 5"
 SETTING_INPUT_ACTION_PLAY_PAUSE_MUSIC: "Reproducir/Pausar la música"
 SETTING_INPUT_ACTION_NEXT_MUSIC_TRACK: "Siguiente pista de música"
 SETTING_INPUT_ACTION_CAMERA_UP: "Desplazar cámara hacia arriba"
 SETTING_INPUT_ACTION_CAMERA_LEFT: "Desplazar cámara a la izquierda"
 SETTING_INPUT_ACTION_CAMERA_DOWN: "Desplazar cámara hacia abajo"
 SETTING_INPUT_ACTION_CAMERA_RIGHT: "Desplazar cámara a la derecha"
 SETTING_INPUT_ACTION_LOCATION_FINDER: "Buscador de ubicaciones"
 SETTING_INPUT_ACTION_OPEN_POLITICS: "Política"
 SETTING_INPUT_ACTION_OPEN_BUDGET: "Presupuesto"
 SETTING_INPUT_ACTION_OPEN_BUILDINGS: "Edificios"
 SETTING_INPUT_ACTION_OPEN_MARKET: "Mercado"
 SETTING_INPUT_ACTION_OPEN_MILITARY: "Ejército"
 SETTING_INPUT_ACTION_OPEN_DIPLOMATIC: "Diplomacia"
 SETTING_INPUT_ACTION_OPEN_TECHNOLOGY: "Tecnología"
 SETTING_INPUT_ACTION_OPEN_SOCIETY: "Sociedad"
 SETTING_INPUT_ACTION_OPEN_POPULATION: "Población"
 SETTING_INPUT_ACTION_OPEN_JOURNAL: "Diario"
 SETTING_INPUT_ACTION_OPEN_POWER_BLOC: "Bloque de poder"
 SETTING_INPUT_ACTION_OPEN_COMPANIES: "Compañías"
 SETTING_INPUT_ACTION_MAP_LIST: "Libro de cuentas"
 SETTING_INPUT_ACTION_BACK: "Atrás"
 SETTING_INPUT_ACTION_OPEN_OUTLINER: "Esquematizador"
 SETTING_INPUT_ACTION_TAB_1: "Pestaña 1"
 SETTING_INPUT_ACTION_TAB_2: "Pestaña 2"
 SETTING_INPUT_ACTION_TAB_3: "Pestaña 3"
 SETTING_INPUT_ACTION_TAB_4: "Pestaña 4"
 SETTING_INPUT_ACTION_TAB_5: "Pestaña 5"
 SETTING_INPUT_ACTION_PRODUCTION_LENS: "Lente de producción"
 SETTING_INPUT_ACTION_POLITICAL_LENS: "Lente política"
 SETTING_INPUT_ACTION_DIPLOMATIC_LENS: "Lente diplomática"
 SETTING_INPUT_ACTION_MILITARY_LENS: "Lente militar"
 SETTING_INPUT_ACTION_TRADE_LENS: "Lente de comercio"
 SETTING_INPUT_ACTION_CONFIRM: "Confirmar"
 SETTING_INPUT_ACTION_CURRENT_SITUATION: "Situación actual"
 SETTING_INPUT_ACTION_CONSTRUCTION_QUEUE: "Cola de construcción"
 SETTING_INPUT_ACTION_TOGGLE_CONSTRUCTION_QUEUE_PAUSE: "Pausar/reanudar cola de construcción"
 SETTING_INPUT_ACTION_GO_TO_DETAILS: "Ir a Detalles"
 SETTING_INPUT_ACTION_SCROLL_UP: "Desplazarse hacia arriba"
 SETTING_INPUT_ACTION_SCROLL_DOWN: "Desplazarse hacia abajo"
 SETTING_INPUT_ACTION_TOGGLE_GUI_DEBUG: "(Depurar) gui.debug"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_PINNED: "Mostrar anclados en el esquematizador"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ECONOMY: "Mostrar Economía en el esquematizador"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_POLITICS: "Mostrar Política en el esquematizador"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_DIPLOMACY: "Mostrar Diplomacia en el esquematizador"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_MILITARY: "Mostrar Ejército en el esquematizador"
 SETTING_INPUT_ACTION_OUTLINER_TOGGLE_ALL: "Mostrar todo en el esquematizador"
 SETTING_INPUT_ACTION_TOGGLE_PIN: "Alternar anclar"
 SETTING_INPUT_ACTION_ZOOM_TO: "Hacer zoom en"
