l_spanish:
 SETTING_AUTOSAVE_TO_CLOUD: "Guardado automático en la nube"
 SETTING_SAVE_FILE_FORMAT: "Formato de guardado por defecto"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Esta opción se anula en los modos de Ironman, guardado en la nube y depuración."
 OPTION_SAVE_FILE_TEXT: "Texto"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Texto comprimido"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Código en binario comprimido"
 SETTING_TOOLTIP_MODE: "Modo ayuda emergente"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nElige cómo deben bloquearse las ayudas emergentes:\n   #b Tendencia del ratón#! - Se bloquea si se mueves el ratón hacia la ayuda emergente.\n   #b Bloqueo temporal#! - Se bloquea después de un tiempo determinado.\n   #b Bloqueo por acción#! - Se bloquea con el botón central del ratón.\n   #b Bloqueo temporal o por acción#! - Se pueden utilizar el bloqueo temporal o el bloqueo por acción."
 SETTING_TOOLTIP_MODE_NO_LOCK: "Sin bloqueo"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Tendencia del ratón"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Bloqueo por acción (anclar ratón)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Bloqueo temporal (anclar ratón)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Bloqueo por acción"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Bloqueo temporal"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Bloqueo temporal o por acción"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nEstablece el tiempo que ha de transcurrir antes de que se muestre la ayuda emergente al pasar por encima de un elemento que incluya una."
 SETTING_TOOLTIP_DELAY: "Mostrar retardo"
 SETTING_TOOLTIP_UNLOCK_TIME: "Retardo de desbloqueo"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nEstablece el tiempo que tardan en desbloquearse las ayudas emergentes."
 SETTING_TOOLTIP_LOCK_TIME: "Retardo de bloqueo"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nEstablece el tiempo que tardan en bloquearse las ayudas emergentes."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Retardo de bloqueo abierto"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nEstablece el tiempo que tardan en bloquearse las ayudas emergentes cuando ya se está mostrando otra ayuda."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Avanzada"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "General"
 SETTINGS_CATEGORY_SFX: "Efectos de sonido"
 SETTINGS_CATEGORY_MFX: "Música"
 SETTINGS_CATEGORY_LANGUAGE: "Idioma"
 SETTINGS_CATEGORY_SAVE_GAMES: "Partidas guardadas"
 SETTINGS_CATEGORY_TOOLTIPS: "Ajustes de la ayuda emergente"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Controles de juego"
 SETTINGS_CATEGORY_MAPMODES: "Modos de mapa"
 SETTING_SHADER_QUALITY: "Calidad de los sombreados"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Calidad de los sombreados\n#!Determina la calidad de los diferentes sombreados y efectos.\n\n#T Alta:#! mejora la calidad de algunos efectos de sombreado a costa del rendimiento.\n\n#T Media:#! ajuste por defecto para disfrutar de la experiencia gráfica esperada.\n\n#T Baja:#! esta opción es perfecta para dispositivos de gama baja. No la recomendamos debido a la pérdida de calidad visual. Se simplifican diferentes sombreados para mejorar el rendimiento gráfico."
 SETTING_SHOW_NUDITY: "Mostrar desnudos"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nDetermina si los personajes pueden aparecer desnudos."
 SETTING_VALUE_HOURS: "$VALUE|0$ h"
 SETTING_VALUE_HOUR_FULL: "$VALUE|0$:00"
 SETTINGS_CATEGORY_DAYNIGHT_CYCLE: "Ciclo de noche-día"
 SETTING_DAYNIGHT_CYCLE: "Activar ciclo de noche-día"
 SETTING_DAYNIGHT_CYCLE_TOOLTIP: "#T $SETTING_DAYNIGHT_CYCLE$#!\nActiva el ciclo de noche-día del movimiento solar."
 SETTING_DAYNIGHT_SYSTEMTIME: "Activar sincronización de la hora local"
 SETTING_DAYNIGHT_SYSTEMTIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SYSTEMTIME$#!\nSincroniza la velocidad del ciclo noche-día y la hora con la hora local del ordenador.\n\n#!Anula la configuración de la velocidad de la simulación."
 SETTING_DAYNIGHT_SPEED: "Velocidad de la simulación"
 SETTING_DAYNIGHT_SPEED_TOOLTIP: "#T $SETTING_DAYNIGHT_SPEED$#!\nVelocidad a la que el día sigue a la noche.#"
 SETTING_SUN_DURATION: "Horas de sol"
 SETTING_SUN_DURATION_TOOLTIP: "#T $SETTING_SUN_DURATION$#!\nCantidad de horas de sol en un día."
 SETTING_SUNRISE_TIME: "Hora del amanecer"
 SETTING_SUNRISE_TIME_TOOLTIP: "#T $SETTING_SUNRISE_TIME$#!\nHora a la que sale el sol.\n\n#!Solo se activa cuando se sincroniza con la hora local.#!"
 SETTING_DAYNIGHT_SET_TIME: "Activar hora manual"
 SETTING_DAYNIGHT_SET_TIME_TOOLTIP: "#T $SETTING_DAYNIGHT_SET_TIME$#!\nEstablece una hora del día concreta.\n\n#!Anula la configuración de la velocidad de simulación y la sincronización con la hora local."
 SETTING_SUNRISE_SET_TIME_HOUR: "Hora manual"
 SETTING_SUNRISE_SET_TIME_HOUR_TOOLTIP: "#T $SETTING_SUNRISE_SET_TIME_HOUR$#!\nBloquea la hora actual.\n\n#!Solo se usa cuando se activa la hora manual.#"
 SETTING_BUILDINGS_CUTOFF: "Sacrificar edificios distantes"
 SETTING_BUILDINGS_CUTOFF_TOOLTIP: "#T $SETTING_BUILDINGS_CUTOFF$#!\nMuestra menos edificios en el mapa cuanto más alejados estén estos de la cámara.\n\nEl rendimiento puede aumentar si se activa esta opción."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Retratos"
 SETTING_SOUNDTRACK: "Música de fondo"
 SETTING_SOUNDTRACK_TOOLTIP: "Música de fondo general"
 SETTING_MUSIC_STINGERS: "Stingers musicales"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Frases musicales cortas para mejorar la partida"
 #Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Música"
 SETTING_AMBIENT: "Ambiente"
 SETTING_MUSIC_TOOLTIP: "#T Volumen de la música\n#!Controla el volumen de la música de fondo."
 SETTING_AMBIENT_TOOLTIP: "#T Volumen ambiental\n#!Controla el volumen del ambiente."
 SETTING_MAP_TOOLTIP_DELAY: "Retardo de ayuda emergente del mapa"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nEstablece el tiempo que tarda en aparecer la ayuda emergente del mapa."
 SETTING_MAP_MODE_DELAY: "Retardo del mapa"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Retardo, en segundos, antes de cambiar a un nuevo modo de mapa."
 SETTING_MAP_MODE_FADE_IN: "Aparición del modo de mapa"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Tiempo, en segundos, que tarda un nuevo modo de mapa en aparecer después de que el anterior desaparezca."
 SETTING_MAP_MODE_FADE_OUT: "Desaparición del modo de mapa"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Tiempo, en segundos, que tarda el modo de mapa actual en desaparecer en función de su retardo al aplicar un nuevo modo de mapa."
 SETTING_OCCUPATION_STRIPES: "Gráficos de ocupación a rayas"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nActiva rayas de colores como gráficos de ocupación en el mapa en vez de texturas con banderas de países"
 SETTING_PORTRAIT_RENDER_SCALE: "Escalado de renderizado de retrato"
 SETTING_PORTRAIT_RENDER_SCALE_TOOLTIP: "#T $SETTING_PORTRAIT_RENDER_SCALE$#!\nMejora el nivel de detalle del retrato del personaje al aumentar la escala de los resultados de renderizado a costa de un poco más de rendimiento del renderizado."
 OPTION_PORTRAIT_RENDER_SCALE_NONE: "×1,0 - Ninguno"
 OPTION_PORTRAIT_RENDER_SCALE_MEDIUM: "×1,5 - Medio"
 OPTION_PORTRAIT_RENDER_SCALE_HIGH: "×2,0 - Alto"
 ui_skin_theme: "Interfaz de usuario"
 ui_skin_theme_desc: "Los botones, marcos, ventanas, cabeceras, etc. del juego."
 papermap_theme: "Mapa de papel"
 papermap_theme_desc: "Este es el mapa que se ve cuando se aleja el zoom."
 table_top_theme: "Mesa de juego"
 table_top_theme_desc: "Si alejas el mapa todo lo posible, se mostrará la mesa en la parte superior e inferior de la pantalla."
 table_asset_1_theme: "Objeto en la mesa (parte superior izquierda)"
 table_asset_1_theme_desc: "El objeto que aparece en la parte superior izquierda de la mesa, junto al mapa, cuando se aleja el zoom."
 table_asset_2_theme: "Objeto en la mesa (parte superior derecha)"
 table_asset_2_theme_desc: "El objeto que aparece en la parte superior derecha de la mesa, junto al mapa, cuando se aleja el zoom."
 table_asset_3_theme: "Objeto de mesa (parte inferior izquierda)"
 table_asset_3_theme_desc: "El objeto que aparece en la parte inferior izquierda de la mesa, junto al mapa, cuando se aleja el zoom."
 table_asset_4_theme: "Objeto de mesa (parte inferior derecha)"
 table_asset_4_theme_desc: "El objeto que aparece en la parte inferior derecha de la mesa, junto al mapa, cuando se aleja el zoom."
 building_sets_themes: "Conjunto de edificios"
 color_blind_mode_test: "Prueba"
